export const APP_STATES = Object.freeze({
  IDLE: "IDLE",
  ANALYZING: "ANALYZING",
  AMBIGUOUS: "AMBIGUOUS",
  NEEDS_AMOUNT: "NEEDS_AMOUNT",
  SUCCESS: "SUCCESS",
  NOT_FOUND: "NOT_FOUND",
  INVALID: "INVALID",
});
