export const AUTH_STATES = Object.freeze({
  SESSION_CHECKING: "SESSION_CHECKING",
  SIGNED_OUT: "SIGNED_OUT",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  VERIFICATION_PENDING: "VERIFICATION_PENDING",
  RESET_REQUESTED: "RESET_REQUESTED",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
  AUTH_ERROR: "AUTH_ERROR",
  AUTHENTICATED_ONBOARDING_REQUIRED: "AUTHENTICATED_ONBOARDING_REQUIRED",
});

